diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.email=gajarw935@gmail.com
user.name=helium01
user.password=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
http.version=HTTP/2
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
credential.helper=osxkeychain
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
user.name=helium01
user.email=fajarw935@gmail.com
user.password=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
remote.origin.url=https://github.com/helium01/kedaireka1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
